#!/usr/bin/env python3
from os import environ, makedirs
import re

target = environ.get('TARGET')
if not target:
    print('::error ::TARGET is required but missing (e.g., x86_64)')
    exit(1)

release_tag = environ.get('RELEASE_TAG')
if not release_tag:
    print('::error ::RELEASE_TAG is required but missing')
    exit(1)

pkg_version = release_tag.lstrip('v')

checksum_file_path = 'release_dist/checksums.txt'
try:
    sha256sum_lines = open(checksum_file_path).readlines()
except FileNotFoundError:
    print(f'::error ::Checksum file missing at {checksum_file_path}')
    exit(1)

word_splitter = re.compile(r'\s+')

def get_checksum(name: str) -> str:
    for line in sha256sum_lines:
        line = line.strip()
        if line.endswith(name):
            checksum, _ = word_splitter.split(line)
            return checksum
    raise KeyError(f'Key {name} does not exist in checksums file')

binary_archive_name = f'emojify-{target}.tar.gz'
checksum = get_checksum(binary_archive_name)

gh_user = "RioTheDev"
gh_repo = "emojify"
maintainer = '# Maintainer: RioTheDev <dateshidze.gio@gmail.com>\n'
# ----------------------------------------------------

readme_url = f'https://raw.githubusercontent.com/{gh_user}/{gh_repo}/{release_tag}/README.md'
license_url = f'https://raw.githubusercontent.com/{gh_user}/{gh_repo}/{release_tag}/LICENSE.md'

opening = maintainer + '\n# This file is automatically generated. Do not edit.\n'

print('Generating PKGBUILD for emojify-bin...')
makedirs('./pkgbuild/emojify-bin', exist_ok=True)
with open('./pkgbuild/emojify-bin/PKGBUILD', 'w') as pkgbuild:
    content = opening + '\n'
    content += 'pkgname=emojify-bin\n'
    content += f'pkgver={pkg_version}\n'
    
    source_url_prefix = f'https://github.com/{gh_user}/{gh_repo}/releases/download/{release_tag}'
    source_url = f'{source_url_prefix}/{binary_archive_name}'
    
    content += f'source=(emojify-{checksum}.tar.gz::{source_url} {readme_url} {license_url})\n'
    content += f'_checksum={checksum}\n'
    
    try:
        content += open('./template/emojify-bin/PKGBUILD').read() + '\n'
    except FileNotFoundError:
        content += '# Template missing. Add your binary installation instructions here.\n'
        
    pkgbuild.write(content)